[package]
name = "huelarm"
version = "0.1.0"
authors = ["Bjarke SÃ¸rensen <bs@wasd.dk>"]

[dependencies]
schedule_recv = "0.1.0"
time = "0.1"

[dependencies.philipshue]
version = "0.2"
default-features = false
features = ["serde_codegen"]